-- Add more artists so users have 40 options (existing 7 + 33 new)
INSERT INTO artists (slug, name, style_description, image_url, sort_order) VALUES
  ('rembrandt', 'Rembrandt', 'baroque painting, dramatic chiaroscuro, deep shadows, golden light, rich browns, portrait mastery, emotional depth, dutch golden age', 'https://picsum.photos/seed/rembrandt/100/100', 8),
  ('vermeer', 'Johannes Vermeer', 'dutch golden age, soft natural light from window, domestic scenes, pearl earrings, calm atmosphere, meticulous detail, subtle colors', 'https://picsum.photos/seed/vermeer/100/100', 9),
  ('caravaggio', 'Caravaggio', 'baroque, tenebrism, dramatic spotlight on figures, dark background, religious drama, intense realism, bold contrast', 'https://picsum.photos/seed/caravaggio/100/100', 10),
  ('michelangelo', 'Michelangelo', 'renaissance, muscular figures, fresco style, monumental scale, sistine chapel, dynamic poses, heroic nude', 'https://picsum.photos/seed/michelangelo/100/100', 11),
  ('leonardo', 'Leonardo da Vinci', 'renaissance, sfumato soft edges, mysterious smile, atmospheric perspective, scientific detail, delicate light', 'https://picsum.photos/seed/leonardo/100/100', 12),
  ('botticelli', 'Sandro Botticelli', 'early renaissance, flowing hair and drapery, mythological themes, birth of venus, delicate line, pastel tones', 'https://picsum.photos/seed/botticelli/100/100', 13),
  ('turner', 'J.M.W. Turner', 'romanticism, seascapes, storms, luminous atmosphere, steam and light, almost abstract swirls of color', 'https://picsum.photos/seed/turner/100/100', 14),
  ('hokusai', 'Hokusai', 'japanese ukiyo-e woodblock print, great wave, mount fuji, bold lines, flat color blocks, blue and white', 'https://picsum.photos/seed/hokusai/100/100', 15),
  ('klimt', 'Gustav Klimt', 'art nouveau, gold leaf, decorative patterns, the kiss, female figures, mosaic-like surfaces, ornamental', 'https://picsum.photos/seed/klimt/100/100', 16),
  ('magritte', 'René Magritte', 'surrealism, bowler hat, pipe, blue sky with clouds, paradoxical imagery, clean realistic technique, belgian', 'https://picsum.photos/seed/magritte/100/100', 17),
  ('warhol', 'Andy Warhol', 'pop art, screen print, repeated imagery, campbell soup, marilyn monroe, bright flat colors, mass media', 'https://picsum.photos/seed/warhol/100/100', 18),
  ('pollock', 'Jackson Pollock', 'abstract expressionism, drip painting, splattered threads of paint, chaotic energy, no clear subject, action painting', 'https://picsum.photos/seed/pollock/100/100', 19),
  ('rothko', 'Mark Rothko', 'color field painting, large soft rectangles, stacked blocks of color, meditative, luminous edges, abstract', 'https://picsum.photos/seed/rothko/100/100', 20),
  ('hopper', 'Edward Hopper', 'american realism, loneliness, diners at night, stark light and shadow, empty streets, cinematic stillness', 'https://picsum.photos/seed/hopper/100/100', 21),
  ('okeeffe', 'Georgia O''Keeffe', 'modernist, large flowers, new mexico desert, bones, soft gradients, sensual organic forms, bold scale', 'https://picsum.photos/seed/okeeffe/100/100', 22),
  ('basquiat', 'Jean-Michel Basquiat', 'neo-expressionism, graffiti, crown, raw text, skulls, bold lines, street art meets museum', 'https://picsum.photos/seed/basquiat/100/100', 23),
  ('mucha', 'Alphonse Mucha', 'art nouveau, decorative panels, flowing hair, floral frames, pale women, poster style, ornamental', 'https://picsum.photos/seed/mucha/100/100', 24),
  ('rousseau', 'Henri Rousseau', 'naive art, jungle scenes, exotic plants, sleeping gypsy, flat perspective, dreamlike, self-taught', 'https://picsum.photos/seed/rousseau/100/100', 25),
  ('kandinsky', 'Wassily Kandinsky', 'abstract, geometric shapes, musical rhythm, bold primary colors, non-representational, bauhaus', 'https://picsum.photos/seed/kandinsky/100/100', 26),
  ('mondrian', 'Piet Mondrian', 'neoplasticism, grid, primary colors red yellow blue, black lines, white space, pure abstraction', 'https://picsum.photos/seed/mondrian/100/100', 27),
  ('chagall', 'Marc Chagall', 'dreamlike, floating figures, village memories, lovers, vibrant color, folk and cubist influence', 'https://picsum.photos/seed/chagall/100/100', 28),
  ('miro', 'Joan Miró', 'surrealism, biomorphic shapes, stars and moons, primary colors, playful, childlike, catalan', 'https://picsum.photos/seed/miro/100/100', 29),
  ('bacon', 'Francis Bacon', 'distorted figures, screaming popes, raw meat, triptych, dark background, existential angst', 'https://picsum.photos/seed/bacon/100/100', 30),
  ('hockney', 'David Hockney', 'bright california pools, palm trees, double portrait, flat vivid color, swimming pools, modern life', 'https://picsum.photos/seed/hockney/100/100', 31),
  ('goya', 'Francisco Goya', 'spanish romanticism, dark period, black paintings, war disasters, haunting, dramatic, psychological', 'https://picsum.photos/seed/goya/100/100', 32),
  ('elgreco', 'El Greco', 'mannerist, elongated figures, dramatic sky, spanish renaissance, mystical, tall saints, vibrant', 'https://picsum.photos/seed/elgreco/100/100', 33),
  ('cezanne', 'Paul Cézanne', 'post-impressionism, geometric blocks, still life apples, mont saint-victoire, constructive brushstrokes', 'https://picsum.photos/seed/cezanne/100/100', 34),
  ('renoir', 'Pierre-Auguste Renoir', 'impressionism, soft light, dancers, luncheon of the boating party, warm skin tones, joyful', 'https://picsum.photos/seed/renoir/100/100', 35),
  ('gauguin', 'Paul Gauguin', 'post-impressionism, tahiti, flat color, tropical women, symbolic, primitivist, bold outlines', 'https://picsum.photos/seed/gauguin/100/100', 36),
  ('toulouselautrec', 'Henri de Toulouse-Lautrec', 'post-impressionism, moulin rouge posters, cabaret, flat color, japonisme, nightlife paris', 'https://picsum.photos/seed/toulouse/100/100', 37),
  ('seurat', 'Georges Seurat', 'pointillism, dots of pure color, sunday afternoon, scientific color theory, neo-impressionism', 'https://picsum.photos/seed/seurat/100/100', 38),
  ('lempicka', 'Tamara de Lempicka', 'art deco, streamlined figures, metallic skin, 1920s glamour, bold geometry, luxury', 'https://picsum.photos/seed/lempicka/100/100', 39),
  ('kusama', 'Yayoi Kusama', 'contemporary, polka dots, infinity mirrors, pumpkins, obsessive repetition, bold colors', 'https://picsum.photos/seed/kusama/100/100', 40)
ON CONFLICT (slug) DO NOTHING;
